### ISSUE TITLE
Failed to add TXT record

### ISSUE THREAD

**Issue by suoji-tarpan** [wjiec/alidns-webhook#11]
创建Cert时报错
E0201 10:51:04.959036       1 alidns.go:57] Failed to add TXT record for "_acme-challenge.abc.com.cn." cause by "Post \"https://alidns.cn-hangzhou.aliyuncs.com/?DomainName=abc.com.cn&KeyWord=_acme-challenge&SearchMode=EXACT&TypeKeyWord=TXT\": net/http: invalid header field value for \"Authorization\""

**Comment by wjiec** [comment]
@suoji-tarpan Very strange! I checked the code in the SDK and the only thing I think is possible is that your `accessKeyId` should have extra control characters like `\n`, if you can please provide the yaml configuration of your issuer and secret (only the accessKeyId is needed, make sure you secure your accessKeySecret)?

**Comment by suoji-tarpan** [comment]
thanks a lot!!!! there is a character '\n' in accessKeyId and accessKeySecret, now, it worked perfectly!!!!
