### ISSUE TITLE
镜像不在白名单中无法拉取

### ISSUE THREAD

**Issue by cwy1996** [wjiec/alidns-webhook#22]
helm后pod提示拉取镜像失败

Failed to pull image "wjiec/alidns-webhook:v1.0.0": failed to pull and unpack image "docker.io/wjiec/alidns-webhook:v1.0.0": failed to copy: httpReadSeeker: failed open: unexpected status code https://docker.m.daocloud.io/v2/wjiec/alidns-webhook/blobs/sha256:9d71258193bd68406e73d5b23da278555d8494c44b55b69286176f521cb0f6e1?ns=docker.io: 403 Forbidden - Server message: denied: 🚫 这镜像不在白名单. this image is not in the allowlist.

**Comment by wjiec** [comment]
Hi, you can use another mirror or some "magic" to get there, I can go ahead and try to add this to the whitelist, but it will take a bit of time, thanks!

**Comment by cwy1996** [comment]
> Hi, you can use another mirror or some "magic" to get there, I can go ahead and try to add this to the whitelist, but it will take a bit of time, thanks!

非常感谢，也希望能早日加入白名单

**Comment by wjiec** [comment]
now we can use the image from the Aliyun registry by adding the `--set image.repository=registry.cn-hangzhou.aliyuncs.com/wjiec/alidns-webhook` parameter to the installation command. The image will be automatically updated via github-action.
