### ISSUE TITLE
Encounter alidns-webhook deploy  error

### ISSUE THREAD

**Issue by Auditore8** [wjiec/alidns-webhook#31]
**Hello wjiec,**

 when I follow the readme to install alidns-webhook, and I encounter a problem of alidns-webhook pod startup. The error message shows that not found the tls.crt file and I double checked the secret it exists. And I also try to mount the same secret **alidns-webhook-tls** with a nginx image ,it shows all the cert files exists and the nginx debug pod is working. So can you give me some suggestion about fixing the issue? Thank  you in advance!
 
Warning  Failed          12s (x4 over 56s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--tls-cert-file=/tls/tls.crt": stat --tls-cert-file=/tls/tls.crt: no such file or directory: unknown

**kubectl get secret alidns-webhook-tls -n cert-manager**
NAME                 TYPE                DATA   AGE
alidns-webhook-tls   kubernetes.io/tls   3      8h

**kubectl describe secret alidns-webhook-tls -n cert-manager**

NAME                 TYPE                DATA   AGE
alidns-webhook-tls   kubernetes.io/tls   3      8h
Name:         alidns-webhook-tls
Namespace:    cert-manager
Labels:       controller.cert-manager.io/fao=true
Annotations:  cert-manager.io/alt-names: alidns-webhook,alidns-webhook.cert-manager,alidns-webhook.cert-manager.svc
              cert-manager.io/certificate-name: alidns-webhook-tls
              cert-manager.io/common-name: 
              cert-manager.io/ip-sans: 
              cert-manager.io/issuer-group: 
              cert-manager.io/issuer-kind: 
              cert-manager.io/issuer-name: alidns-webhook-ca
              cert-manager.io/uri-sans: 

Type:  kubernetes.io/tls

Data
ca.crt:   1143 bytes
tls.crt:  1212 bytes
tls.key:  1675 bytes

**k describe pod alidns-webhook-599bcd5bb9-s6wvz -n cert-manager**
Name:             alidns-webhook-599bcd5bb9-s6wvz
Namespace:        cert-manager
Priority:         0
Service Account:  alidns-webhook
Start Time:       Fri, 06 Dec 2024 15:34:25 +0800
Labels:           app.kubernetes.io/instance=alidns-webhook
                  app.kubernetes.io/name=alidns-webhook
                  pod-template-hash=599bcd5bb9
Controlled By:  ReplicaSet/alidns-webhook-599bcd5bb9
Containers:
  alidns-webhook:
    Args:
      --tls-cert-file=/tls/tls.crt
      --tls-private-key-file=/tls/tls.key
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--tls-cert-file=/tls/tls.crt": stat --tls-cert-file=/tls/tls.crt: no such file or directory: unknown
      Exit Code:    128
    Ready:          False
    Restart Count:  3
    Liveness:       http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    **Mounts:
      /tls from certs (ro)**
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8qxt2 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
**Volumes:
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alidns-webhook-tls
    Optional:    false**
  kube-api-access-8qxt2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true

**Comment by Auditore8** [comment]
kubernetes version: 1.31
certmanager version:1.16.2
helm: 3.15.3

**Comment by wjiec** [comment]
Hi @Auditore8 thanks for the detailed logs, it seems that there is something wrong with your installation of alidns-webhook and the Container's image in your Pod is missing. Below is the result of my execution of `kubectl -n cert-manager describe po alidns-webhook-7db6bf4949-klmvg`:
```plain
Name:             alidns-webhook-7db6bf4949-klmvg
Namespace:        cert-manager
Priority:         0
Service Account:  alidns-webhook
Node:             kind-1.31.0-worker2/172.17.0.3
Start Time:       Fri, 06 Dec 2024 09:59:13 +0000
Labels:           app.kubernetes.io/instance=alidns-webhook
                  app.kubernetes.io/name=alidns-webhook
                  pod-template-hash=7db6bf4949
Annotations:      <none>
Status:           Running
IP:               10.244.2.4
IPs:
  IP:           10.244.2.4
Controlled By:  ReplicaSet/alidns-webhook-7db6bf4949
Containers:
  alidns-webhook:
    Container ID:  containerd://6009e26e6543d0636864ccd2e9a96cafdb5223fa7f34b389b4c0add0a0bf59ea
    Image:         wjiec/alidns-webhook:v1.0.1     <===== HERE
    Image ID:      docker.io/wjiec/alidns-webhook@sha256:82bb1c87da86e5243787dc22776b39c0ef5a25f4c1046703c5afc763918df8b5
    Port:          443/TCP
    Host Port:     0/TCP
    Args:
      --tls-cert-file=/tls/tls.crt
      --tls-private-key-file=/tls/tls.key
    State:          Running
      Started:      Fri, 06 Dec 2024 09:59:22 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GROUP_NAME:  acme.yourcompany.com
    Mounts:
      /tls from certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2569n (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       True
  ContainersReady             True
  PodScheduled                True
Volumes:
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alidns-webhook-tls
    Optional:    false
  kube-api-access-2569n:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

Look at the contents of `Containers -> alidns-webhook -> Image`.

Can you provide the full yaml configuration of the pod(`kubectl -n cert-manager get <pod> -o yaml`)? Or I'm guessing there might be some controller in your cluster that tries to modify the Pod's image settings?

**Comment by Auditore8** [comment]
Hi @wjiec  ,
Due to some sentive info, sorry I did't show all the info about image. Here is the output of pod.  As I 'm unable to pull dockerhub image directly, so I pull it with bastion and push it to my own aliyun registry.  

 **k describe pod alidns-webhook-6c5cb7874d-5ggz5  -n cert-manager**
Name:             alidns-webhook-6c5cb7874d-5ggz5
Namespace:        cert-manager
Priority:         0
Service Account:  alidns-webhook
Node:             cn-heyuan.10.**.215.111/10.**.215.111
Start Time:       Fri, 06 Dec 2024 18:01:06 +0800
Labels:           app.kubernetes.io/instance=alidns-webhook
                  app.kubernetes.io/name=alidns-webhook
                  pod-template-hash=6c5cb7874d
Annotations:      k8s.aliyun.com/pod-ips: 10.**.39.207
Status:           Running
IP:               10.**.39.207
IPs:
  IP:           10.**.39.207
Controlled By:  ReplicaSet/alidns-webhook-6c5cb7874d
Containers:
  alidns-webhook:
    Container ID:  containerd://399f99666896ee8ef119e8240218d45****9e56faa0c31b8d41eceb01bc47cff0
    Image:         *****-registry.cn-beijing.cr.aliyuncs.com/default/*****/public/alidns-webhook:v1.0.1
    Image ID:      *****-registry.cn-beijing.cr.aliyuncs.com/default/*****/public/alidns-webhook@sha256:a36ca8272c34130da178573cf76001a1329f0***ac21017e04e1eea3768ae09e
    Port:          443/TCP
    Host Port:     0/TCP
    Args:
      --tls-cert-file=/tls/tls.crt
      --tls-private-key-file=/tls/tls.key
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--tls-cert-file=/tls/tls.crt": stat --tls-cert-file=/tls/tls.crt: no such file or directory: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 08:00:00 +0800
      Finished:     Fri, 06 Dec 2024 18:06:50 +0800
    Ready:          False
    Restart Count:  6
    Liveness:       http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GROUP_NAME:  acme.****.com.cn
    Mounts:
      /tls from certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pthk9 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alidns-webhook-tls
    Optional:    false
  kube-api-access-pthk9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   Scheduled       8m4s                  default-scheduler  Successfully assigned cert-manager/alidns-webhook-6c5cb7874d-5ggz5 to cn-heyuan.10.**.215.111
  Normal   AllocIPSucceed  8m5s                  terway-daemon      Alloc IP 10.**.39.207/22 took 27.624982ms
  Normal   Pulled          6m27s (x5 over 8m4s)  kubelet            Container image "********-registry.cn-beijing.cr.aliyuncs.com/default/*******/public/alidns-webhook:v1.0.1" already present on machine
  Normal   Created         6m27s (x5 over 8m4s)  kubelet            Created container alidns-webhook
  Warning  Failed          6m27s (x5 over 8m4s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--tls-cert-file=/tls/tls.crt": stat --tls-cert-file=/tls/tls.crt: no such file or directory: unknown
  Warning  BackOff         3m (x29 over 8m2s)    kubelet            Back-off restarting failed container alidns-webhook in pod alidns-webhook-6c5cb7874d-5ggz5_cert-manager(9a5c4e86-f2d5-46f4-8d06-0981153f72d8)

**Comment by wjiec** [comment]
@Auditore8 You are right, from the content of this look down, I feel that the image in your private registry is a bit of a problem, the normal container execution command is `container.command + container.args`, perhaps because you push the content of this image is not correct or the address is wrong, resulting in the loss of `container.command`, then it becomes a direct execution of the `container.args`. You can use docker to pull this image, and then try to use docker run to start it, I use `docker run -ti --rm wjiec/alidns-webhook:v1.0.1` to get the output is:
```plain
panic: GROUP_NAME must be specified

goroutine 1 [running]:
main.main()
	/workspace/main.go:14 +0xb4
```
Using `docker inspect wjiec/alidns-webhook:v1.0.1` gets the output:
```plain
[
    {
        "Id": "sha256:8c774324a3516a91949fd4837465106dd2cfdce86dedf1a0485b9732c8d72676",
        "RepoTags": [
            "wjiec/alidns-webhook:v1.0.1"
        ],
        "RepoDigests": [
            "wjiec/alidns-webhook@sha256:82bb1c87da86e5243787dc22776b39c0ef5a25f4c1046703c5afc763918df8b5"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-10-03T04:49:26.596229441Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "alidns-webhook"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.created": "2024-10-03T04:47:59.308Z",
                "org.opencontainers.image.description": "alidns-webhook is a generic ACME solver for cert-manager.",
                "org.opencontainers.image.licenses": "MIT",
                "org.opencontainers.image.revision": "56104b6a9e238580ab73168f221d50775db8eba6",
                "org.opencontainers.image.source": "https://github.com/wjiec/alidns-webhook",
                "org.opencontainers.image.title": "alidns-webhook",
                "org.opencontainers.image.url": "https://github.com/wjiec/alidns-webhook",
                "org.opencontainers.image.version": "v1.0.1"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 71900636,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/dc06da1734deb081f353eeb584e90ddd3a620c08d5a55a87023cc619dcb12235/diff",
                "MergedDir": "/var/lib/docker/overlay2/cf53035015e5e8a9fb06224aa16f4d1fe2dc0246b5380822dd37a1ec8ce02bc3/merged",
                "UpperDir": "/var/lib/docker/overlay2/cf53035015e5e8a9fb06224aa16f4d1fe2dc0246b5380822dd37a1ec8ce02bc3/diff",
                "WorkDir": "/var/lib/docker/overlay2/cf53035015e5e8a9fb06224aa16f4d1fe2dc0246b5380822dd37a1ec8ce02bc3/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:5181257c7956c691316e978aef13e2365e12e5f164337a2b7910d829d657d6c5",
                "sha256:30c2064aa1b7ffa999150617d8afee3c6cd35901663d4528ded4f727835f8e10"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by Auditore8** [comment]
Hi @wjiec ,
Thanks for the debugging, yes, the root cause is the image. After I use the dockerhub image with some magic, the webhook works as expected.
