### ISSUE TITLE
kubelet  MountVolume.SetUp failed for volume "certs" : secret "alidns-webhook-tls" not found

### ISSUE THREAD

**Issue by yunkaiOr2** [wjiec/alidns-webhook#9]
Name:             alidns-webhook-8596b8dfcf-z9s22
Namespace:        cert-manager
Priority:         0
Service Account:  alidns-webhook
Node:             m6e/10.168.1.172
Start Time:       Thu, 18 Jan 2024 00:03:50 +0800
Labels:           app.kubernetes.io/instance=alidns-webhook
                  app.kubernetes.io/name=alidns-webhook
                  pod-template-hash=8596b8dfcf
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/alidns-webhook-8596b8dfcf
Containers:
  alidns-webhook:
    Container ID:  
    Image:         wjiec/alidns-webhook:v0.1.0
    Image ID:      
    Port:          443/TCP
    Host Port:     0/TCP
    Args:
      --tls-cert-file=/tls/tls.crt
      --tls-private-key-file=/tls/tls.key
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GROUP_NAME:  acme.yourcompany.com
    Mounts:
      /tls from certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4cgnm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alidns-webhook-tls
    Optional:    false
  kube-api-access-4cgnm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                 From     Message
  ----     ------       ----                ----     -------
  Warning  FailedMount  25s (x271 over 8h)  kubelet  MountVolume.SetUp failed for volume "certs" : secret "alidns-webhook-tls" not found

**Comment by wjiec** [comment]
Hi, it looks like your cert-manager is not installed correctly? The `alidns-webhook-tls` is issued by cert-manager via the manifest [pki.yaml](https://github.com/wjiec/alidns-webhook/blob/main/charts/alidns-webhook/templates/pki.yaml).

**Comment by yunkaiOr2** [comment]
my fail, cert-manager proxy failed
